language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
    - libqt4-dev

script:
  - qmake && make
  - cd tests
  - for i in ./tst_*; do ./$i; done
